#!/usr/bin/env python3
"""Copy only public website files to dist/. Never publish source, tests or reports."""
from pathlib import Path
import json, shutil
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
MARKER='.readykin-staged'

def main():
    manifest=json.loads((ROOT/'site-src/data/build-manifest.json').read_text())
    if OUT.exists():
        if OUT.is_symlink() or not (OUT/MARKER).is_file():
            raise SystemExit('Refusing to replace an unrecognized dist directory. Rename it first.')
        shutil.rmtree(OUT)
    OUT.mkdir();(OUT/MARKER).write_text('Generated by ReadyKin stage-site.py\n')
    public=[v['file'] for v in manifest['pages'].values()]+[
        'readykin.css','readykin.js','discovery.css','discovery.js','style.css',
        'favicon.ico','favicon.png','apple-touch-icon.png','CNAME','.nojekyll',
        'robots.txt','sitemap.xml','app-ads.txt','.well-known/apple-app-site-association',
        manifest['indexnow_key_file']]
    if manifest.get('verification_file'):public.append(manifest['verification_file'])
    public.extend(str(p.relative_to(ROOT)) for p in (ROOT/'images').rglob('*') if p.is_file())
    for name in public:
        src=ROOT/name
        if not src.is_file() or src.is_symlink() or not src.resolve().is_relative_to(ROOT):
            raise SystemExit(f'Missing or unsafe public file: {name}')
        dest=OUT/name;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dest)
    print(f'Staged {len(public)} public files in dist/. Source, docs and reports excluded.')
if __name__=='__main__':main()
